Velocity no crash
[18:32:22] [epollEventLoopGroup-4-1/WARN] [geyser]: Extension Boar loads class it.unimi.dsi.fastutil.longs.Long2ObjectMap from an external source. This can change at any time and break the extension, additionally to potentially causing unexpected behaviour!
[18:32:22] [epollEventLoopGroup-4-1/ERROR] [org.geysermc.geyser.event.GeyserEventBus]: An exception occurred while executing event SessionLoginEvent for subscriber org.geysermc.geyser.event.GeyserEventSubscriber
java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/longs/Long2ObjectMap
	at ac.boar.anticheat.player.BoarPlayer.<init>(BoarPlayer.java:58) ~[?:?]
	at ac.boar.anticheat.player.manager.BoarPlayerManager.add(BoarPlayerManager.java:17) ~[?:?]
	at ac.boar.geyser.GeyserBoar.onSessionJoin(GeyserBoar.java:27) ~[?:?]
	at org.lanternpowered.lmbda.Lmbda$49.accept(Unknown Source) ~[velocity.jar:3.4.0-SNAPSHOT (git-21ecd344-b509)]
	at org.geysermc.event.subscribe.impl.SubscriberImpl.lambda$new$0(SubscriberImpl.java:55) ~[?:?]